###
# * App Configuration Keys
# 1.) Duplicate and rename this file `env.yml`
# 2.) Set any required and desired optional values.
# 3.) Remove optional values you don't wish to use.
###

# str [REQUIRED]: Set your bot access token here.
DISCORD_BOT_TOKEN: ''

# str [OPTIONAL]: Set your GitHub access token here.
GITHUB_ACCESS_TOKEN: ''

# list(int) [OPTIONAL]: List any priority server ID's to sync when bot launches.
DISCORD_GUILD_IDS: []

# bool(0,1) [OPTIONAL]: Governs whether upscaling commands can only be used by the server owner.
OWNER_ONLY: 0

# int(1-16) [OPTIONAL]: Governs the max scale value allowed for supported by the bot.
MAX_MODEL_SCALE: 4

# int(1-3) [OPTIONAL]: Governs the min inputChannels allowed for supported models.
# NOTE: 1 is Grayscale (colorless), 2 is RGB, 3 is RGBA (allows transparency).
MIN_COLORS_IN: 3

# int(1-3) [OPTIONAL]: Governs the min outputChannels allowed for supported models.
MIN_COLORS_OUT: 3
