###
# * App Configuration Keys
# 1.) Duplicate and rename this file `env.yml`
# 2.) Set any required and desired optional values.
# 3.) Remove optional values you don't wish to use.
###

# str [REQUIRED]: Set your bot access token here.
DISCORD_BOT_TOKEN: ''

# str [OPTIONAL]: Set your GitHub access token here.
GITHUB_ACCESS_TOKEN: ''

# list(int) [OPTIONAL]: List any priority server ID's to sync when bot launches.
DISCORD_GUILD_IDS: []

# bool(0,1) [OPTIONAL]: Governs whether upscaling commands can only be used by the server owner.
OWNER_ONLY: 0

# int(1-16) [OPTIONAL]: Governs the max scale value allowed for supported by the bot.
MAX_MODEL_SCALE: 4

# int(1-3) [OPTIONAL]: Governs the min inputChannels allowed for supported models.
# NOTE: 1 is Grayscale (colorless), 2 is RGB, 3 is RGBA (allows transparency).
MIN_COLORS_IN: 3

# int(1-3) [OPTIONAL]: Governs the min outputChannels allowed for supported models.
MIN_COLORS_OUT: 3

MAX_SIZE:
  # int(0+) [OPTIONAL]: Max dimension allowed for submitted images being processed by a 1X model.
  # Images with dimensions at or below this number will be processed as-is.
  # Images with dimensions at or above this number will be split into tiles, the tiles will
  # be upscaled individually and recombined afterward.
  # Setting this value to 0 will allow images of all sizes. NOT RECOMMENDED!
  X1: 4000

  # int(0+) [OPTIONAL]: Max dimension allowed for submitted images being processed by a >1X, <4X model.
  # Setting this value to 0 will allow images of all sizes. NOT RECOMMENDED!
  X2: 3000

  # int(0+) [OPTIONAL]: Max dimension allowed for submitted images being processed by a >=4X, <6X model.
  # Setting this value to 0 will allow images of all sizes. NOT RECOMMENDED!
  X4: 2000

  # int(0+) [OPTIONAL]: Max dimension allowed for submitted images being processed by a >=6X, <8X model.
  # Setting this value to 0 will allow images of all sizes. NOT RECOMMENDED!
  X6: 1200

  # int(0+) [OPTIONAL]: Max dimension allowed for submitted images being processed by a 8X model.
  # Setting this value to 0 will allow images of all sizes. NOT RECOMMENDED!
  X8: 1000

# Setting this to 0 will disable tiling altogether which is NOT RECOMMENDED! Unless you have
# a very competent GPU (think Nvidia 4090).
TILE_SIZE: 512

# Sets the fallback TILE_SIZE when the above TILE_SIZE is too large for very demanding models.
# Setting this to 0 will disable tiling fallback altogether which is NOT RECOMMENDED! Unless you have a very
# competent GPU (think Nvidia 4090).
TILE_SIZE_FALLBACK: 256
